/**
 * JustTCG セットIDから日本語名へのマッピング
 * 主要セット（M/SV/S/SM時代）の公式日本語名
 * セットコード（SV10, M3等）は set_code フィールドに別途保存されるため、ここでは収録弾名のみ
 */
export const SET_NAME_JA: Record<string, string> = {
  // === M (Mega) 時代 ===
  'm3-nihil-zero-pokemon-japan': 'ムニキスゼロ',
  'mp1-start-deck-100-corocoro-comic-pokemon-japan': 'スタートデッキ100 コロコロコミックver.',
  'start-deck-100-battle-collection-pokemon-japan': 'スタートデッキ100 バトルコレクション',
  'm2a-high-class-pack-mega-dream-ex-pokemon-japan': 'ハイクラスパック MEGAドリームex',
  'm2-inferno-x-pokemon-japan': 'インフェルノX',
  'mbg-mega-starter-set-mega-gengar-ex-pokemon-japan': 'MEGAスターターセット メガゲンガーex',
  'mbd-mega-starter-set-mega-diancie-ex-pokemon-japan': 'MEGAスターターセット メガディアンシーex',
  'm-p-promotional-cards-pokemon-japan': 'プロモカード',
  'm1s-mega-symphonia-pokemon-japan': 'メガシンフォニア',
  'm1l-mega-brave-pokemon-japan': 'メガブレイブ',

  // === SV (Scarlet & Violet) 時代 ===
  'scarlet-violet-energies-pokemon-japan': 'スカーレット&バイオレット エネルギー',
  'sv11w-white-flare-pokemon-japan': 'ホワイトフレア',
  'sv11b-black-bolt-pokemon-japan': 'ブラックボルト',
  'sv10-the-glory-of-team-rocket-pokemon-japan': 'ロケット団の栄光',
  'sv9a-heat-wave-arena-pokemon-japan': 'ヒートウェーブアリーナ',
  'sv9-battle-partners-pokemon-japan': 'バトルパートナーズ',
  'svn-battle-partners-deck-build-box-pokemon-japan': 'バトルパートナーズ デッキビルドBOX',
  'sv8a-terastal-fest-ex-pokemon-japan': 'テラスタルフェスex',
  'svm-generations-start-decks-pokemon-japan': 'ジェネレーションスタートデッキ',
  'sv8-super-electric-breaker-pokemon-japan': '超電ブレイカー',
  'sv-p-promotional-cards-pokemon-japan': 'プロモカード',
  'sv7a-paradise-dragona-pokemon-japan': '楽園ドラゴーナ',
  'sv7-stellar-miracle-pokemon-japan': 'ステラミラクル',
  'sv-stellar-miracle-deck-build-box-pokemon-japan': 'ステラミラクル デッキビルドBOX',
  'sv6a-night-wanderer-pokemon-japan': 'ナイトワンダラー',
  'sv6-transformation-mask-pokemon-japan': '変幻の仮面',
  'sv5a-crimson-haze-pokemon-japan': 'クリムゾンヘイズ',
  'sv5m-cyber-judge-pokemon-japan': 'サイバージャッジ',
  'sv5k-wild-force-pokemon-japan': 'ワイルドフォース',
  'sv4a-shiny-treasure-ex-pokemon-japan': 'シャイニートレジャーex',
  'sv4m-future-flash-pokemon-japan': '未来の一閃',
  'sv4k-ancient-roar-pokemon-japan': '古代の咆哮',
  'sv3a-raging-surf-pokemon-japan': 'レイジングサーフ',
  'sv3-ruler-of-the-black-flame-pokemon-japan': '黒炎の支配者',
  'sv-ruler-of-the-black-flame-deck-build-box-pokemon-japan': '黒炎の支配者 デッキビルドBOX',
  'sv2a-pokemon-card-151-pokemon-japan': 'ポケモンカード151',
  'sv2p-snow-hazard-pokemon-japan': 'スノーハザード',
  'sv2d-clay-burst-pokemon-japan': 'クレイバースト',
  'sv1a-triplet-beat-pokemon-japan': 'トリプレットビート',
  'sv1v-violet-ex-pokemon-japan': 'バイオレットex',
  'sv1s-scarlet-ex-pokemon-japan': 'スカーレットex',
  'sv-premium-trainer-box-ex-pokemon-japan': 'プレミアムトレーナーボックスex',
  'sv-ex-start-decks-pokemon-japan': 'exスタートデッキ',
  'sv-ex-special-set-pokemon-japan': 'exスペシャルセット',
  'sv-ex-starter-set-pikachu-ex-pawmot-pokemon-japan': 'exスターターセット ピカチュウex&パーモット',
  'sv-ex-starter-set-sprigatito-lucario-ex-pokemon-japan': 'exスターターセット ニャオハ&ルカリオex',
  'sv-ex-starter-set-quaxly-mimikyu-ex-pokemon-japan': 'exスターターセット クワッス&ミミッキュex',
  'sv-ex-starter-set-fuecoco-ampharos-ex-pokemon-japan': 'exスターターセット ホゲータ&デンリュウex',
  'sv-ex-starter-set-steven-s-beldum-metagross-ex-pokemon-japan': 'exスターターセット ダイゴのダンバル&メタグロスex',
  'sv-ex-starter-set-marnie-s-morpeko-grimmsnarl-ex-pokemon-japan': 'exスターターセット マリィのモルペコ&オーロンゲex',
  'sv-mewtwo-ex-terastal-starter-set-pokemon-japan': 'ミュウツーex テラスタルスターターセット',
  'sv-skeledirge-ex-terastal-starter-set-pokemon-japan': 'ラウドボーンex テラスタルスターターセット',
  'sv-ceruledge-ex-stellar-tera-type-starter-set-pokemon-japan': 'ソウブレイズex ステラテラタイプ スターターセット',
  'sv-sylveon-ex-stellar-tera-type-starter-set-pokemon-japan': 'ニンフィアex ステラテラタイプ スターターセット',
  'sv-chien-pao-ex-battle-master-deck-pokemon-japan': 'パオジアンex バトルマスターデッキ',
  'sv-terastal-charizard-ex-battle-master-deck-pokemon-japan': 'テラスタルリザードンex バトルマスターデッキ',
  'sv-venusaur-charizard-blastoise-special-deck-set-pokemon-japan': 'フシギバナ・リザードン・カメックス スペシャルデッキセット',
  'sv-future-miraidon-ex-starter-deck-build-set-pokemon-japan': '未来のミライドンex スターターデッキ&ビルドセット',
  'sv-ancient-koraidon-ex-starter-deck-build-set-pokemon-japan': '古代のコライドンex スターターデッキ&ビルドセット',
  'pokemon-tcg-classic-venusaur-pokemon-japan': 'ポケモンTCGクラシック フシギバナ',
  'pokemon-tcg-classic-charizard-pokemon-japan': 'ポケモンTCGクラシック リザードン',
  'pokemon-tcg-classic-blastoise-pokemon-japan': 'ポケモンTCGクラシック カメックス',
  'wcs23-2023-world-championships-yokohama-deck-pikachu-pokemon-japan': '2023 ワールドチャンピオンシップス 横浜デッキ ピカチュウ',
  'special-box-collections-pokemon-japan': 'スペシャルBOXコレクション',
  'battle-academy-pokemon-japan': 'バトルアカデミー',

  // === S (Sword & Shield) 時代 ===
  's12a-vstar-universe-pokemon-japan': 'VSTARユニバース',
  's12-paradigm-trigger-pokemon-japan': 'パラダイムトリガー',
  's11a-incandescent-arcana-pokemon-japan': '白熱のアルカナ',
  's11-lost-abyss-pokemon-japan': 'ロストアビス',
  's10b-pokemon-go-pokemon-japan': 'ポケモンGO',
  's10a-dark-phantasma-pokemon-japan': 'ダークファンタズマ',
  's10p-space-juggler-pokemon-japan': 'スペースジャグラー',
  's10d-time-gazer-pokemon-japan': 'タイムゲイザー',
  's9a-battle-region-pokemon-japan': 'バトルリージョン',
  's9-star-birth-pokemon-japan': 'スターバース',
  's8b-vmax-climax-pokemon-japan': 'VMAXクライマックス',
  's8a-25th-anniversary-collection-pokemon-japan': '25thアニバーサリーコレクション',
  's8a-g-25th-anniversary-golden-box-pokemon-japan': '25thアニバーサリー ゴールデンBOX',
  's8-fusion-arts-pokemon-japan': 'フュージョンアーツ',
  's7d-skyscraping-perfection-pokemon-japan': '摩天パーフェクト',
  's7r-blue-sky-stream-pokemon-japan': '蒼空ストリーム',
  's6a-eevee-heroes-pokemon-japan': 'イーブイヒーローズ',
  's6k-jet-black-spirit-pokemon-japan': '漆黒のガイスト',
  's6h-silver-lance-pokemon-japan': '白銀のランス',
  's5a-peerless-fighters-pokemon-japan': '双璧のファイター',
  's5r-rapid-strike-master-pokemon-japan': '連撃マスター',
  's5i-single-strike-master-pokemon-japan': '一撃マスター',
  's4a-shiny-star-v-pokemon-japan': 'シャイニースターV',
  's4-amazing-volt-tackle-pokemon-japan': '仰天のボルテッカー',
  's3a-legendary-heartbeat-pokemon-japan': '伝説の鼓動',
  's3-infinity-zone-pokemon-japan': 'ムゲンゾーン',
  's2a-explosive-walker-pokemon-japan': '爆炎ウォーカー',
  's2-rebellion-crash-pokemon-japan': '反逆クラッシュ',
  's1a-vmax-rising-pokemon-japan': 'VMAXライジング',
  's1w-sword-pokemon-japan': 'ソード',
  's1h-shield-pokemon-japan': 'シールド',
  's-p-sword-shield-promos-pokemon-japan': 'ソード&シールド プロモ',
  'si-start-deck-100-pokemon-japan': 'スタートデッキ100',
  'sp6-vstar-special-set-pokemon-japan': 'VSTARスペシャルセット',
  'sp5-v-union-special-card-sets-pokemon-japan': 'V-UNIONスペシャルカードセット',
  'sp4-eevee-heroes-vmax-special-set-pokemon-japan': 'イーブイヒーローズ VMAXスペシャルセット',
  'sp2-vmax-special-set-pokemon-japan': 'VMAXスペシャルセット',
  'sp1-zacian-zamazenta-box-pokemon-japan': 'ザシアン+ザマゼンタ BOX',
  'ss-gengar-vmax-high-class-deck-pokemon-japan': 'ゲンガーVMAX ハイクラスデッキ',
  'ss-inteleon-vmax-high-class-deck-pokemon-japan': 'インテレオンVMAX ハイクラスデッキ',
  'ss-silver-lance-jet-black-spirit-jumbo-pack-set-pokemon-japan': '白銀のランス&漆黒のガイスト ジャンボパックセット',
  'sf-single-strike-rapid-strike-premium-trainer-boxes-pokemon-japan': '一撃&連撃 プレミアムトレーナーBOX',
  'sd-v-starter-decks-pokemon-japan': 'Vスタートデッキ',
  'sc-charizard-starter-set-vmax-pokemon-japan': 'リザードン スターターセットVMAX',
  'sc-grimmsnarl-starter-set-vmax-pokemon-japan': 'オーロンゲ スターターセットVMAX',
  'sc2-charizard-starter-set-vmax-2-pokemon-japan': 'リザードン スターターセットVMAX 2',
  'sb-sword-shield-premium-trainer-box-pokemon-japan': 'ソード&シールド プレミアムトレーナーBOX',
  'sn-start-deck-100-corocoro-comic-version-pokemon-japan': 'スタートデッキ100 コロコロコミックver.',
  'sld-darkrai-starter-set-vstar-pokemon-japan': 'ダークライ スターターセットVSTAR',
  'sll-lucario-starter-set-vstar-pokemon-japan': 'ルカリオ スターターセットVSTAR',
  'sk-vstar-premium-trainer-box-pokemon-japan': 'VSTARプレミアムトレーナーBOX',
  'sj-zacian-zamazenta-vs-eternatus-special-deck-set-pokemon-japan': 'ザシアン&ザマゼンタ vs ムゲンダイナ スペシャルデッキセット',
  's8a-p-promo-card-pack-25th-anniversary-edition-pokemon-japan': 'プロモカードパック 25thアニバーサリーedition',
  'sef-venusaur-starter-set-vmax-pokemon-japan': 'フシギバナ スターターセットVMAX',
  'sek-blastoise-starter-set-vmax-pokemon-japan': 'カメックス スターターセットVMAX',
  'sh-sword-shield-family-pokemon-card-game-pokemon-japan': 'ソード&シールド ファミリーポケモンカードゲーム',
  's0-charizard-vstar-vs-rayquaza-vmax-special-deck-set-pokemon-japan': 'リザードンVSTAR vs レックウザVMAX スペシャルデッキセット',
  'spd-deoxys-vstar-vmax-high-class-deck-pokemon-japan': 'デオキシスVSTAR&VMAX ハイクラスデッキ',
  'spz-zeraora-vstar-vmax-high-class-deck-pokemon-japan': 'ゼラオラVSTAR&VMAX ハイクラスデッキ',
  'sa-water-starter-set-v-pokemon-japan': '水タイプ スターターセットV',
  'sa-fighting-starter-set-v-pokemon-japan': '闘タイプ スターターセットV',
  'sa-lightning-starter-set-v-pokemon-japan': '雷タイプ スターターセットV',
  'sa-fire-starter-set-v-pokemon-japan': '炎タイプ スターターセットV',
  'sa-grass-starter-set-v-pokemon-japan': '草タイプ スターターセットV',

  // === SM (Sun & Moon) 時代 ===
  'sm12a-tag-team-gx-tag-all-stars-pokemon-japan': 'TAG TEAM GX タッグオールスターズ',
  'sm12-alter-genesis-pokemon-japan': 'オルタージェネシス',
  'sm11b-dream-league-pokemon-japan': 'ドリームリーグ',
  'sm11a-remix-bout-pokemon-japan': 'リミックスバウト',
  'sm11-miracle-twin-pokemon-japan': 'ミラクルツイン',
  'sm10b-sky-legend-pokemon-japan': 'スカイレジェンド',
  'sm10a-gg-end-pokemon-japan': 'GGエンド',
  'sm10-double-blaze-pokemon-japan': 'ダブルブレイズ',
  'sm9b-full-metal-wall-pokemon-japan': 'フルメタルウォール',
  'sm9a-night-unison-pokemon-japan': 'ナイトユニゾン',
  'sm9-tag-bolt-pokemon-japan': 'タッグボルト',
  'sm8b-gx-ultra-shiny-pokemon-japan': 'GXウルトラシャイニー',
  'sm8a-dark-order-pokemon-japan': 'ダークオーダー',
  'sm8-super-burst-impact-pokemon-japan': '超爆インパクト',
  'sm7b-fairy-rise-pokemon-japan': 'フェアリーライズ',
  'sm7a-thunderclap-spark-pokemon-japan': '迅雷スパーク',
  'sm7-sky-splitting-charisma-pokemon-japan': '裂空のカリスマ',
  'sm6b-champion-road-pokemon-japan': 'チャンピオンロード',
  'sm6a-dragon-storm-pokemon-japan': 'ドラゴンストーム',
  'sm6-forbidden-light-pokemon-japan': '禁断の光',
  'sm5-ultra-force-pokemon-japan': 'ウルトラフォース',
  'sm5m-ultra-moon-pokemon-japan': 'ウルトラムーン',
  'sm5s-ultra-sun-pokemon-japan': 'ウルトラサン',
  'sm4-gx-battle-boost-pokemon-japan': 'GXバトルブースト',
  'sm4a-ultradimensional-beasts-pokemon-japan': '超次元の暴獣',
  'sm4s-awakened-heroes-pokemon-japan': '覚醒の勇者',
  'sm3-shining-legends-pokemon-japan': 'ひかる伝説',
  'sm3h-to-have-seen-the-battle-rainbow-pokemon-japan': '闘う虹を見たか',
  'sm3n-darkness-that-consumes-light-pokemon-japan': '光を喰らう闇',
  'sm2-facing-a-new-trial-pokemon-japan': '新たなる試練の向こう',
  'sm2k-islands-await-you-pokemon-japan': 'キミを待つ島々',
  'sm2l-alolan-moonlight-pokemon-japan': 'アローラの月光',
  'sm1-enhanced-expansion-pack-sun-moon-pokemon-japan': '強化拡張パック サン&ムーン',
  'sm1s-collection-sun-pokemon-japan': 'コレクション サン',
  'sm1m-collection-moon-pokemon-japan': 'コレクション ムーン',
  'sm-the-best-of-xy-pokemon-japan': 'THE BEST OF XY',
  'sm-p-sun-moon-promos-pokemon-japan': 'サン&ムーン プロモ',
  'sm0-pikachu-s-new-friends-pokemon-japan': 'ピカチュウの新しい仲間',
  'smm-tag-team-gx-starter-sets-pokemon-japan': 'TAG TEAM GX スターターセット',
  'smj-tag-team-gx-premium-trainer-box-pokemon-japan': 'TAG TEAM GX プレミアムトレーナーBOX',
  'smh-gx-starter-decks-pokemon-japan': 'GXスタートデッキ',
  'smk-trainer-battle-decks-pokemon-japan': 'トレーナーバトルデッキ',
  'sml-sun-moon-family-pokemon-card-game-pokemon-japan': 'サン&ムーン ファミリーポケモンカードゲーム',
  'smp2-great-detective-pikachu-pokemon-japan': '名探偵ピカチュウ',
  'smp1-rockruff-full-power-deck-pokemon-japan': 'イワンコ フルパワーデッキ',
  'sma-sun-moon-starter-set-pokemon-japan': 'サン&ムーン スターターセット',
  'smb-premium-trainer-box-pokemon-japan': 'プレミアムトレーナーBOX',
  'smc-tapu-bulu-gx-enhanced-starter-set-pokemon-japan': 'カプ・ブルルGX 強化スターターセット',
  'smd-ash-vs-team-rocket-deck-kit-pokemon-japan': 'サトシ vs ロケット団 デッキキット',
  'sme-solgaleo-gx-lunala-gx-legendary-starter-set-pokemon-japan': 'ソルガレオGX&ルナアーラGX レジェンダリースターターセット',
  'smf-ultra-sun-ultra-moon-premium-trainer-box-pokemon-japan': 'ウルトラサン&ウルトラムーン プレミアムトレーナーBOX',
  'smi-flareon-gx-vaporeon-gx-jolteon-gx-starter-sets-pokemon-japan': 'ブースターGX・シャワーズGX・サンダースGX スターターセット',

  // === XY 時代 ===
  'cp6-expansion-pack-20th-anniversary-pokemon-japan': '拡張パック 20thアニバーサリー',
  'cp5-mythical-legendary-dream-shine-collection-pokemon-japan': '幻・伝説ドリームキラコレクション',
  'cp4-premium-champion-pack-pokemon-japan': 'プレミアムチャンピオンパック',
  'cp3-pokekyun-collection-pokemon-japan': 'ポケキュンコレクション',
  'cp2-legendary-shine-collection-pokemon-japan': 'レジェンダリーシャインコレクション',
  'cp1-magma-gang-vs-aqua-gang-double-crisis-pokemon-japan': 'マグマ団 vs アクア団 ダブルクライシス',
  'xy11-br-cruel-traitor-pokemon-japan': '冷酷の反逆者',
  'xy11-bb-fever-burst-fighter-pokemon-japan': '爆熱の闘士',
  'xy10-awakening-psychic-king-pokemon-japan': 'めざめる超王',
  'xy9-rage-of-the-broken-heavens-pokemon-japan': '破天の怒り',
  'xy8-br-red-flash-pokemon-japan': 'レッドフラッシュ',
  'xy8-bb-blue-shock-pokemon-japan': 'ブルーショック',
  'xy7-bandit-ring-pokemon-japan': 'バンデットリング',
  'xy6-emerald-break-pokemon-japan': 'エメラルドブレイク',
  'xy5-bt-tidal-storm-pokemon-japan': 'タイダルストーム',
  'xy5-bg-gaia-volcano-pokemon-japan': 'ガイアボルケーノ',
  'xy4-phantom-gate-pokemon-japan': 'ファントムゲート',
  'xy3-rising-fist-pokemon-japan': 'ライジングフィスト',
  'xy2-wild-blaze-pokemon-japan': 'ワイルドブレイズ',
  'xy-bx-collection-x-pokemon-japan': 'コレクションX',
  'xy-by-collection-y-pokemon-japan': 'コレクションY',
  'xy-p-xy-promos-pokemon-japan': 'XYプロモ',
  'xy-beginning-set-pokemon-japan': 'XYはじめてセット',
  'break-starter-pack-pokemon-japan': 'BREAKスターターパック',

  // === 旧裏 / その他 ===
  'japanese-cd-promo-pokemon-japan': 'CDプロモ',
  'expansion-pack-pokemon-japan': '第1弾 拡張パック',
  'expansion-pack-no-rarity-pokemon-japan': '第1弾 拡張パック (レアリティなし)',
  'pokemon-jungle-pokemon-japan': 'ポケモンジャングル',
  'mystery-of-the-fossils-pokemon-japan': '化石の秘密',
  'rocket-gang-pokemon-japan': 'ロケット団',
  'gym-challenge-pokemon-japan': 'ジムチャレンジ',
  'challenge-from-the-darkness-pokemon-japan': '闇からの挑戦',
  'leaders-stadium-pokemon-japan': 'リーダーズスタジアム',
  'gold-silver-to-a-new-world-pokemon-japan': '金、銀、新世界へ…',
  'crossing-the-ruins-pokemon-japan': '遺跡をこえて…',
  'awakening-legends-pokemon-japan': '目覚める伝説',
  'darkness-and-to-light-pokemon-japan': '闇、そして光へ…',
  'pokemon-web-pokemon-japan': 'ポケモンWeb',
  'pokemon-vs-pokemon-japan': 'ポケモンVS',
  'southern-island-pokemon-japan': 'サザンアイランド',
  'corocoro-promotional-cards-pokemon-japan': 'コロコロプロモカード',

  // === BW (Black & White) 時代 ===
  'bw-extra-regulation-box-pokemon-japan': 'BW エクストラレギュレーションBOX',
  'bw9-megalo-cannon-pokemon-japan': 'メガロキャノン',
  'bw8-spiral-force-pokemon-japan': 'ラセンフォース',
  'bw8-thunder-knuckle-pokemon-japan': 'サンダーナックル',
  'bw7-plasma-gale-pokemon-japan': 'プラズマゲイル',
  'bw6-cold-flare-pokemon-japan': 'コールドフレア',
  'bw6-freeze-bolt-pokemon-japan': 'フリーズボルト',
  'bw5-dragon-blast-pokemon-japan': 'ドラゴンブラスト',
  'bw5-dragon-blade-pokemon-japan': 'ドラゴンブレード',
  'bw4-dark-rush-pokemon-japan': 'ダークラッシュ',
  'bw3-psycho-drive-pokemon-japan': 'サイコドライブ',
  'bw3-hail-blizzard-pokemon-japan': 'ヘイルブリザード',
  'bw2-red-collection-pokemon-japan': 'レッドコレクション',
  'bw1-black-collection-pokemon-japan': 'ブラックコレクション',
  'bw1-white-collection-pokemon-japan': 'ホワイトコレクション',
  'bw-p-promotional-cards-pokemon-japan': 'BW-P プロモカード',
  'ex-battle-boost-pokemon-japan': 'EXバトルブースト',
  'shiny-collection-pokemon-japan': 'シャイニーコレクション',
  'dragon-selection-pokemon-japan': 'ドラゴンセレクション',
  'master-deck-build-box-ex-pokemon-japan': 'マスターデッキビルドBOX EX',
  'team-plasma-battle-gift-set-pokemon-japan': 'プラズマ団 バトルギフトセット',
  'team-plasma-s-powered-half-deck-pokemon-japan': 'プラズマ団 パワードハーフデッキ',
  'everyone-s-exciting-battle-pokemon-japan': 'みんなのわくわくバトル',
  'bkb-black-kyurem-ex-battle-strength-deck-pokemon-japan': 'ブラックキュレムEX バトル強化デッキ',
  'bkw-white-kyurem-ex-battle-strength-deck-pokemon-japan': 'ホワイトキュレムEX バトル強化デッキ',
  'bkz-zekrom-ex-battle-strength-deck-pokemon-japan': 'ゼクロムEX バトル強化デッキ',
  'bkr-reshiram-ex-battle-strength-deck-pokemon-japan': 'レシラムEX バトル強化デッキ',
  'bk-terrakion-battle-strength-deck-pokemon-japan': 'テラキオン バトル強化デッキ',
  'bk-cobalion-battle-strength-deck-pokemon-japan': 'コバルオン バトル強化デッキ',
  'bk-virizion-battle-strength-deck-pokemon-japan': 'ビリジオン バトル強化デッキ',
  'keldeo-battle-strength-deck-pokemon-japan': 'ケルディオ バトル強化デッキ',
  'garchomp-half-deck-pokemon-japan': 'ガブリアス ハーフデッキ',
  'hydreigon-half-deck-pokemon-japan': 'サザンドラ ハーフデッキ',
  'battle-gift-set-thundurus-vs-tornadus-pokemon-japan': 'バトルギフトセット ボルトロスvsトルネロス',
  'battle-theme-deck-victini-pokemon-japan': 'バトルテーマデッキ ビクティニ',
  'blastoise-kyurem-ex-combo-deck-pokemon-japan': 'カメックス+キュレムEX コンボデッキ',
  'mewtwo-vs-genesect-deck-kit-mewtwo-pokemon-japan': 'ミュウツーvsゲノセクト デッキキット（ミュウツー）',
  'mewtwo-vs-genesect-deck-kit-genesect-pokemon-japan': 'ミュウツーvsゲノセクト デッキキット（ゲノセクト）',
  'cs1-journey-partners-collection-sheet-pokemon-japan': '旅立ちの仲間たち コレクションシート',

  // === LEGEND / L 時代 ===
  'l3-clash-at-the-summit-pokemon-japan': '頂上大激突',
  'll-lost-link-pokemon-japan': 'ロストリンク',
  'l2-revival-legends-pokemon-japan': 'よみがえる伝説',
  'l2-steelix-constructed-standard-deck-pokemon-japan': 'ハガネール 構築スタンダードデッキ',
  'l2-tyranitar-constructed-standard-deck-pokemon-japan': 'バンギラス 構築スタンダードデッキ',
  'l1-soulsilver-collection-pokemon-japan': 'ソウルシルバーコレクション',
  'l1-heartgold-collection-pokemon-japan': 'ハートゴールドコレクション',
  'l-p-legends-promos-pokemon-japan': 'LEGEND プロモカード',
  'leafeon-vs-metagross-expert-deck-metagross-pokemon-japan': 'リーフィアvsメタグロス エキスパートデッキ（メタグロス）',
  'leafeon-vs-metagross-expert-deck-leafeon-pokemon-japan': 'リーフィアvsメタグロス エキスパートデッキ（リーフィア）',
  'battle-starter-deck-blastoise-pokemon-japan': 'バトルスタートデッキ（カメックス）',
  'battle-starter-deck-magmortar-pokemon-japan': 'バトルスタートデッキ（ブーバーン）',
  'battle-starter-deck-torterra-pokemon-japan': 'バトルスタートデッキ（ドダイトス）',
  'battle-starter-deck-raichu-pokemon-japan': 'バトルスタートデッキ（ライチュウ）',
  'movie-commemoration-random-pack-pokemon-japan': '劇場版公開記念ランダムパック',
  'melee-pokemon-scramble-pokemon-japan': '乱戦！ポケモンスクランブル',

  // === DP / Pt 時代 ===
  'pt4-advent-of-arceus-pokemon-japan': 'アルセウス光臨',
  'pt3-beat-of-the-frontier-pokemon-japan': '破空の激戦',
  'pt2-bonds-to-the-end-of-time-pokemon-japan': '時の果ての絆',
  'pt1-galactic-s-conquest-pokemon-japan': 'ギンガ団の野望',
  'dp5-cry-from-the-mysterious-pokemon-japan': '秘境の叫び',
  'dp5-temple-of-anger-pokemon-japan': '怒りの神殿',
  'dp4-moonlit-pursuit-pokemon-japan': '月光の追跡',
  'dp4-dawn-dash-pokemon-japan': '夜明けの疾走',
  'dp3-shining-darkness-pokemon-japan': '光の果てに',
  'dp2-secret-of-the-lakes-pokemon-japan': '湖の秘密',
  'dp1-space-time-creation-pokemon-japan': '時空の創造',
  'dp-p-promotional-cards-pokemon-japan': 'DP-P プロモカード',
  'dpt-p-promotional-cards-pokemon-japan': 'DPt-P プロモカード',
  'pts-shaymin-lv-x-collection-pack-pokemon-japan': 'シェイミLV.X コレクションパック',
  'ptr-regigigas-lv-x-collection-pack-pokemon-japan': 'レジギガスLV.X コレクションパック',
  'ptm-mewtwo-lv-x-collection-pack-pokemon-japan': 'ミュウツーLV.X コレクションパック',
  'arceus-lv-x-deck-grass-fire-pokemon-japan': 'アルセウスLV.Xデッキ 草＆炎',
  'arceus-lv-x-deck-lightning-psychic-pokemon-japan': 'アルセウスLV.Xデッキ 雷＆超',
  'garchomp-vs-charizard-sp-deck-kit-garchomp-pokemon-japan': 'ガブリアスVSリザードン SPデッキキット（ガブリアス）',
  'garchomp-vs-charizard-sp-deck-kit-charizard-pokemon-japan': 'ガブリアスVSリザードン SPデッキキット（リザードン）',
  'infernape-vs-gallade-sp-deck-kit-gallade-pokemon-japan': 'ゴウカザルVSエルレイド SPデッキキット（エルレイド）',
  'infernape-vs-gallade-sp-deck-kit-infernape-pokemon-japan': 'ゴウカザルVSエルレイド SPデッキキット（ゴウカザル）',
  'giratina-vs-dialga-deck-kit-giratina-pokemon-japan': 'ギラティナVSディアルガ デッキキット（ギラティナ）',
  'giratina-vs-dialga-deck-kit-dialga-pokemon-japan': 'ギラティナVSディアルガ デッキキット（ディアルガ）',
  'heatran-vs-regigigas-deck-kit-pokemon-japan': 'ヒードランVSレジギガス デッキキット',
  'magmortar-vs-electivire-deck-kit-pokemon-japan': 'ブーバーンVSエレキブル デッキキット',
  'dpt-gift-box-pikachu-pokemon-japan': 'DPt ギフトボックス（ピカチュウ）',
  'dpt-gift-box-turtwig-pokemon-japan': 'DPt ギフトボックス（ナエトル）',
  'dpt-gift-box-chimchar-pokemon-japan': 'DPt ギフトボックス（ヒコザル）',
  'dpt-gift-box-piplup-pokemon-japan': 'DPt ギフトボックス（ポッチャマ）',
  'entry-pack-dpt-palkia-pokemon-japan': 'エントリーパックDPt（パルキア）',
  'entry-pack-dpt-giratina-pokemon-japan': 'エントリーパックDPt（ギラティナ）',
  'entry-pack-dpt-dialga-pokemon-japan': 'エントリーパックDPt（ディアルガ）',
  'entry-pack-08-pokemon-japan': "エントリーパック'08",
  'entry-pack-pokemon-japan': 'エントリーパック',
  'intense-fight-in-the-destroyed-sky-pokemon-japan': '破空の激闘',
  'dialga-lv-x-constructed-standard-deck-pokemon-japan': 'ディアルガLV.X 構築スタンダードデッキ',
  'palkia-lv-x-constructed-standard-deck-pokemon-japan': 'パルキアLV.X 構築スタンダードデッキ',
  'bastiodon-the-defender-half-deck-pokemon-japan': 'トリデプス ハーフデッキ',
  'rampardos-the-attacker-constructed-half-deck-pokemon-japan': 'ラムパルド ハーフデッキ',
  'world-champions-pack-pokemon-japan': 'ワールドチャンピオンズパック',
  '11th-movie-commemoration-set-pokemon-japan': '劇場版11周年記念セット',
  '10th-movie-commemoration-set-pokemon-japan': '劇場版10周年記念プレミアムシート',
  'ppp-promotional-cards-pokemon-japan': 'PPP プロモカード',
  'movie-commemoration-vs-pack-sea-s-manaphy-pokemon-japan': '劇場版公開記念VSパック 海のマナフィ',

  // === XY 追加（デッキキット等）===
  'xyg-zygarde-ex-perfect-battle-deck-pokemon-japan': 'ジガルデEX パーフェクトバトルデッキ',
  'xyh-m-audino-ex-mega-battle-deck-pokemon-japan': 'Mタブンネ EX メガバトルデッキ',
  'xyf-golduck-break-palkia-ex-combo-deck-pokemon-japan': 'ゴルダックBREAK+パルキアEX コンボデッキ',
  'xye-emboar-ex-vs-togekiss-ex-deck-kit-pokemon-japan': 'エンブオーEX vs トゲキッスEX デッキキット',
  'xyd-m-rayquaza-ex-mega-battle-deck-pokemon-japan': 'MレックウザEX メガバトルデッキ',
  'xyc-super-legend-set-xerneas-ex-yveltal-ex-pokemon-japan': 'スーパーレジェンドセット ゼルネアスEX＆イベルタルEX',
  'xyb-dialga-ex-aegislash-ex-hyper-metal-chain-deck-pokemon-japan': 'ディアルガEX+ギルガルドEX ハイパーメタルチェーンデッキ',
  'xya-m-charizard-ex-mega-battle-deck-pokemon-japan': 'MリザードンEX メガバトルデッキ',
  'yveltal-half-deck-pokemon-japan': 'イベルタル ハーフデッキ',
  'xerneas-half-deck-pokemon-japan': 'ゼルネアス ハーフデッキ',
  'snp-noivern-break-evolution-pack-pokemon-japan': 'オンバーンBREAK進化パック',
  'snp-raichu-break-evolution-pack-pokemon-japan': 'ライチュウBREAK進化パック',
  'm-master-deck-build-box-power-style-pokemon-japan': 'MマスターデッキビルドBOX パワースタイル',
  'm-master-deck-build-box-speed-style-pokemon-japan': 'MマスターデッキビルドBOX スピードスタイル',

  // === PCG / ADV / e-card 時代 ===
  'holon-phantom-pokemon-japan': 'ホロンの幻影',
  'holon-research-tower-pokemon-japan': 'ホロンの研究塔',
  'holon-research-tower-water-quarter-deck-pokemon-japan': 'ホロンの研究塔 水クォーターデッキ',
  'holon-research-tower-lightning-quarter-deck-pokemon-japan': 'ホロンの研究塔 雷クォーターデッキ',
  'holon-research-tower-fire-quarter-deck-pokemon-japan': 'ホロンの研究塔 炎クォーターデッキ',
  'gift-box-mew-lucario-mightyena-quarter-deck-pokemon-japan': 'ギフトボックス ミュウ・ルカリオ（グラエナ クォーターデッキ）',
  'gift-box-mew-lucario-pokemon-star-pokemon-japan': 'ギフトボックス ミュウ・ルカリオ（ポケモン☆）',
  'gift-box-mew-lucario-crawdaunt-quarter-deck-pokemon-japan': 'ギフトボックス ミュウ・ルカリオ（シザリガー クォーターデッキ）',
  'gift-box-mew-lucario-lucario-quarter-deck-pokemon-japan': 'ギフトボックス ミュウ・ルカリオ（ルカリオ クォーターデッキ）',
  'gift-box-mew-lucario-mew-quarter-deck-pokemon-japan': 'ギフトボックス ミュウ・ルカリオ（ミュウ クォーターデッキ）',
  'mirage-forest-pokemon-japan': '幻影の森',
  'mirage-s-mew-constructed-starter-deck-pokemon-japan': '幻影のミュウ 構築スターターデッキ',
  'golden-sky-silvery-ocean-pokemon-japan': '金の空、銀の海',
  'pokepark-forest-pokemon-japan': 'ポケパークの森',
  'movie-commemoration-vs-pack-aura-s-lucario-pokemon-japan': '劇場版公開記念VSパック 波導のルカリオ',
  'master-kit-side-deck-pokemon-japan': 'マスターキット（サイドデッキ）',
  'master-kit-bulbasaur-pokemon-japan': 'マスターキット（フシギダネ）',
  'meganium-constructed-starter-deck-pokemon-japan': 'メガニウム 構築スターターデッキ',
  'typhlosion-constructed-starter-deck-pokemon-japan': 'バクフーン 構築スターターデッキ',
  'feraligatr-constructed-starter-deck-pokemon-japan': 'オーダイル 構築スターターデッキ',
  'offense-and-defense-of-the-furthest-ends-pokemon-japan': 'さいはての攻防',
  'miracle-crystal-pokemon-japan': 'ミラクルクリスタル',
  'earth-s-groudon-ex-constructed-starter-deck-pokemon-japan': '大地のグラードンex 構築スターターデッキ',
  'ocean-s-kyogre-ex-constructed-starter-deck-pokemon-japan': '海のカイオーガex 構築スターターデッキ',
  'imprison-gardevoir-ex-constructed-standard-deck-pokemon-japan': '封印！サーナイトex 構築スタンダードデッキ',
  'shockwave-tyranitar-ex-constructed-standard-deck-pokemon-japan': '衝撃！バンギラスex 構築スタンダードデッキ',
  'rocket-gang-strikes-back-pokemon-japan': 'ロケット団の逆襲',
  'clash-of-the-blue-sky-pokemon-japan': '蒼空の激突',
  'flight-of-legends-pokemon-japan': '伝説の飛翔',
  'undone-seal-pokemon-japan': '解放された封印',
  'rulers-of-the-heavens-pokemon-japan': '天空の覇者',
  'miracle-of-the-desert-pokemon-japan': '砂漠のきせき',
  'magma-vs-aqua-two-ambitions-pokemon-japan': 'マグマVSアクア ふたつの野望',
  'movie-commemoration-vs-pack-pokemon-japan': '劇場版公開記念VSパック',
  'movie-commemoration-vs-pack-sky-splitting-deoxys-pokemon-japan': '劇場版公開記念VSパック 裂空のデオキシス',
  'rayquaza-constructed-starter-deck-pokemon-japan': '構築済みスターター レックウザ',
  'deoxys-constructed-starter-deck-pokemon-japan': '構築済みスターター デオキシス',
  'metagross-constructed-starter-deck-pokemon-japan': '構築済みスターター メタグロス',
  'salamence-constructed-starter-deck-pokemon-japan': '構築済みスターター ボーマンダ',
  'flygon-constructed-starter-deck-pokemon-japan': '構築済みスターター フライゴン',
  'torchic-constructed-starter-deck-pokemon-japan': '構築済みスターター アチャモ',
  'treecko-constructed-starter-deck-pokemon-japan': '構築済みスターター キモリ',
  'mudkip-constructed-starter-deck-pokemon-japan': '構築済みスターター ミズゴロウ',
  'adv-expansion-pack-pokemon-japan': 'ADV 拡張パック',
  'gift-box-latias-pokemon-japan': 'ギフトボックス（ラティアス）',
  'gift-box-latios-pokemon-japan': 'ギフトボックス（ラティオス）',
  'emerald-gift-box-rayquaza-pokemon-japan': 'エメラルドギフトボックス（レックウザ）',
  'emerald-gift-box-deoxys-pokemon-japan': 'エメラルドギフトボックス（デオキシス）',
  'aqua-deck-kit-pokemon-japan': 'アクアデッキキット',
  'magma-deck-kit-pokemon-japan': 'マグマデッキキット',
  'black-deck-kit-pokemon-japan': 'ブラックデッキキット',
  'silver-deck-kit-pokemon-japan': 'シルバーデッキキット',
  'pcg-p-promotional-cards-pokemon-japan': 'PCG-P プロモカード',
  'play-promotional-cards-pokemon-japan': 'PLAY プロモカード',
  'adv-p-promotional-cards-pokemon-japan': 'ADV-P プロモカード',

  // === e-card / Web / その他 ===
  'mysterious-mountains-pokemon-japan': 'ふしぎな山々',
  'split-earth-pokemon-japan': '大地の裂け目',
  'wind-from-the-sea-pokemon-japan': '海からの風',
  'the-town-on-no-map-pokemon-japan': '地図にない町',
  'theater-limited-vs-pack-pokemon-japan': '劇場限定VSパック',
  'base-expansion-pack-pokemon-japan': '第1弾 基本拡張パック',
  'pokemon-e-starter-deck-pokemon-japan': 'ポケモンe スターターデッキ',
  'mcdonald-s-pokemon-e-minimum-pack-pokemon-japan': 'マクドナルド ポケモンe ミニマムパック',
  't-promotional-cards-pokemon-japan': 'T プロモカード',
  'p-promotional-cards-pokemon-japan': 'P プロモカード',
  'water-quick-construction-pack-pokemon-japan': '水 クイックコンストラクションパック',
  'lightning-quick-construction-pack-pokemon-japan': '雷 クイックコンストラクションパック',
  'psychic-quick-construction-pack-pokemon-japan': '超 クイックコンストラクションパック',
  'fighting-quick-construction-pack-pokemon-japan': '闘 クイックコンストラクションパック',
  'fire-quick-construction-pack-pokemon-japan': '炎 クイックコンストラクションパック',
  'grass-quick-construction-pack-pokemon-japan': '草 クイックコンストラクションパック',

  // === Neo / 旧裏 追加 ===
  'intro-pack-neo-chikorita-pokemon-japan': 'イントロパックNeo（チコリータ）',
  'intro-pack-neo-totodile-pokemon-japan': 'イントロパックNeo（ワニノコ）',
  'intro-pack-squirtle-pokemon-japan': 'イントロパック（ゼニガメ）',
  'intro-pack-bulbasaur-pokemon-japan': 'イントロパック（フシギダネ）',
  'neo-premium-file-3-pokemon-japan': 'Neoプレミアムファイル3',
  'neo-premium-file-2-pokemon-japan': 'Neoプレミアムファイル2',
  'neo-premium-file-1-pokemon-japan': 'Neoプレミアムファイル1',
  'quick-starter-gift-set-red-deck-pokemon-japan': 'クイックスターターギフトセット（赤デッキ）',
  'quick-starter-gift-set-green-deck-pokemon-japan': 'クイックスターターギフトセット（緑デッキ）',
  'city-gym-decks-pokemon-japan': 'シティジムデッキ',
  'world-hobby-fair-pokemon-japan': 'ワールドホビーフェア',
  'unnumbered-promotional-cards-pokemon-japan': 'ナンバーなしプロモカード',
  'champion-road-pokemon-japan': 'チャンピオンロード',
  'pokemon-card-fan-club-pokemon-japan': 'ポケモンカードファンクラブ',
  'battle-road-pokemon-japan': 'バトルロード',
  'pokemon-card-information-promotional-cards-pokemon-japan': 'ポケモンカード情報 プロモカード',
  'vending-machine-cards-series-1-blue-pokemon-japan': '自動販売機カード 第1弾（青）',
  'vending-machine-cards-series-2-red-pokemon-japan': '自動販売機カード 第2弾（赤）',
  'vending-machine-cards-series-3-green-pokemon-japan': '自動販売機カード 第3弾（緑）',
}

/**
 * セットIDから日本語名を取得（マッピングがなければ英語名を返す）
 */
export function getSetNameJa(id: string, fallbackName: string): string {
  return SET_NAME_JA[id] || fallbackName
}

/**
 * セットIDからset_code（例: "SV10", "M3", "SLD"）を抽出
 * "sv10-the-glory-of-team-rocket-pokemon-japan" → "SV10"
 * "m3-nihil-zero-pokemon-japan" → "M3"
 * "sld-darkrai-starter-set-vstar-pokemon-japan" → "SLD"
 * "sv-p-promotional-cards-pokemon-japan" → "SV-P"
 * R12-22: 数字なしのコード（SLD, SK等）にも対応
 * R14-13: プロモ（-P）やサブセット（-Br, -Bb, -G等）のハイフン入りコードにも対応
 * R14-14: 偽陽性防止（最大4文字 + 英語単語除外）
 */
export function extractSetCode(setId: string): string | null {
  // ハイフン入りサブコード（-P, -Br, -Bb, -G 等）を含むパターンを先に試行
  const subMatch = setId.match(/^([a-z]{1,4}\d*[a-z]?-[a-z]{1,2})-/i)
  if (subMatch) return subMatch[1].toUpperCase()
  // 通常パターン（最大4文字のプレフィックス + 任意の数字 + 任意の末尾英字1文字）
  const match = setId.match(/^([a-z]{1,4}\d+[a-z]?)-/i)
    || setId.match(/^(s[a-z]{0,3}\d*[a-z]?)-/i) // S/SV/SM/SJ/SK等のS系
    || setId.match(/^(m\d+|cp\d+|xy\d*|dp\d*|bw\d*|wcs\d*)-/i) // 既知のプレフィックス
  return match ? match[1].toUpperCase() : null
}

/**
 * release_dateから年を抽出
 * "2026-01-23" → 2026
 * R14-18: ISO日付の先頭4桁を明示的に抽出し、範囲検証
 */
export function extractReleaseYear(releaseDate: string | null): number | null {
  if (!releaseDate) return null
  const m = releaseDate.match(/^(\d{4})-/)
  if (!m) return null
  const year = parseInt(m[1])
  return (year >= 1996 && year <= 2100) ? year : null
}
