/**
 * JustTCG セットIDから日本語名へのマッピング
 * 主要セット（M/SV/S/SM時代）の公式日本語名
 */
export const SET_NAME_JA: Record<string, string> = {
  // === M (Mega) 時代 ===
  'm3-nihil-zero-pokemon-japan': 'M3: ニヒルゼロ',
  'mp1-start-deck-100-corocoro-comic-pokemon-japan': 'MP1: スタートデッキ100 コロコロコミックver.',
  'start-deck-100-battle-collection-pokemon-japan': 'スタートデッキ100 バトルコレクション',
  'm2a-high-class-pack-mega-dream-ex-pokemon-japan': 'M2a: ハイクラスパック MEGAドリームex',
  'm2-inferno-x-pokemon-japan': 'M2: インフェルノX',
  'mbg-mega-starter-set-mega-gengar-ex-pokemon-japan': 'MBG: MEGAスターターセット メガゲンガーex',
  'mbd-mega-starter-set-mega-diancie-ex-pokemon-japan': 'MBD: MEGAスターターセット メガディアンシーex',
  'm-p-promotional-cards-pokemon-japan': 'M-P: プロモカード',
  'm1s-mega-symphonia-pokemon-japan': 'm1S: メガシンフォニア',
  'm1l-mega-brave-pokemon-japan': 'm1L: メガブレイブ',

  // === SV (Scarlet & Violet) 時代 ===
  'scarlet-violet-energies-pokemon-japan': 'スカーレット&バイオレット エネルギー',
  'sv11w-white-flare-pokemon-japan': 'SV11W: ホワイトフレア',
  'sv11b-black-bolt-pokemon-japan': 'SV11B: ブラックボルト',
  'sv10-the-glory-of-team-rocket-pokemon-japan': 'SV10: ロケット団の栄光',
  'sv9a-heat-wave-arena-pokemon-japan': 'SV9a: ヒートウェーブアリーナ',
  'sv9-battle-partners-pokemon-japan': 'SV9: バトルパートナーズ',
  'svn-battle-partners-deck-build-box-pokemon-japan': 'SVN: バトルパートナーズ デッキビルドBOX',
  'sv8a-terastal-fest-ex-pokemon-japan': 'SV8a: テラスタルフェスex',
  'svm-generations-start-decks-pokemon-japan': 'SVM: ジェネレーションスタートデッキ',
  'sv8-super-electric-breaker-pokemon-japan': 'SV8: 超電ブレイカー',
  'sv-p-promotional-cards-pokemon-japan': 'SV-P: プロモカード',
  'sv7a-paradise-dragona-pokemon-japan': 'SV7a: パラダイスドラゴナ',
  'sv7-stellar-miracle-pokemon-japan': 'SV7: ステラミラクル',
  'sv-stellar-miracle-deck-build-box-pokemon-japan': 'SV: ステラミラクル デッキビルドBOX',
  'sv6a-night-wanderer-pokemon-japan': 'SV6a: ナイトワンダラー',
  'sv6-transformation-mask-pokemon-japan': 'SV6: 変幻の仮面',
  'sv5a-crimson-haze-pokemon-japan': 'SV5a: クリムゾンヘイズ',
  'sv5m-cyber-judge-pokemon-japan': 'SV5M: サイバージャッジ',
  'sv5k-wild-force-pokemon-japan': 'SV5K: ワイルドフォース',
  'sv4a-shiny-treasure-ex-pokemon-japan': 'SV4a: シャイニートレジャーex',
  'sv4m-future-flash-pokemon-japan': 'SV4M: 未来の一閃',
  'sv4k-ancient-roar-pokemon-japan': 'SV4K: 古代の咆哮',
  'sv3a-raging-surf-pokemon-japan': 'SV3a: レイジングサーフ',
  'sv3-ruler-of-the-black-flame-pokemon-japan': 'SV3: 黒炎の支配者',
  'sv-ruler-of-the-black-flame-deck-build-box-pokemon-japan': 'SV: 黒炎の支配者 デッキビルドBOX',
  'sv2a-pokemon-card-151-pokemon-japan': 'SV2a: ポケモンカード151',
  'sv2p-snow-hazard-pokemon-japan': 'SV2P: スノーハザード',
  'sv2d-clay-burst-pokemon-japan': 'SV2D: クレイバースト',
  'sv1a-triplet-beat-pokemon-japan': 'SV1a: トリプレットビート',
  'sv1v-violet-ex-pokemon-japan': 'SV1V: バイオレットex',
  'sv1s-scarlet-ex-pokemon-japan': 'SV1S: スカーレットex',
  'sv-premium-trainer-box-ex-pokemon-japan': 'SV: プレミアムトレーナーボックスex',
  'sv-ex-start-decks-pokemon-japan': 'SV: exスタートデッキ',
  'sv-ex-special-set-pokemon-japan': 'SV: exスペシャルセット',
  'sv-ex-starter-set-pikachu-ex-pawmot-pokemon-japan': 'SV: exスターターセット ピカチュウex&パーモット',
  'sv-ex-starter-set-sprigatito-lucario-ex-pokemon-japan': 'SV: exスターターセット ニャオハ&ルカリオex',
  'sv-ex-starter-set-quaxly-mimikyu-ex-pokemon-japan': 'SV: exスターターセット クワッス&ミミッキュex',
  'sv-ex-starter-set-fuecoco-ampharos-ex-pokemon-japan': 'SV: exスターターセット ホゲータ&デンリュウex',
  'sv-ex-starter-set-steven-s-beldum-metagross-ex-pokemon-japan': 'SV: exスターターセット ダイゴのダンバル&メタグロスex',
  'sv-ex-starter-set-marnie-s-morpeko-grimmsnarl-ex-pokemon-japan': 'SV: exスターターセット マリィのモルペコ&オーロンゲex',
  'sv-mewtwo-ex-terastal-starter-set-pokemon-japan': 'SV: ミュウツーex テラスタルスターターセット',
  'sv-skeledirge-ex-terastal-starter-set-pokemon-japan': 'SV: ラウドボーンex テラスタルスターターセット',
  'sv-ceruledge-ex-stellar-tera-type-starter-set-pokemon-japan': 'SV: ソウブレイズex ステラテラタイプ スターターセット',
  'sv-sylveon-ex-stellar-tera-type-starter-set-pokemon-japan': 'SV: ニンフィアex ステラテラタイプ スターターセット',
  'sv-chien-pao-ex-battle-master-deck-pokemon-japan': 'SV: パオジアンex バトルマスターデッキ',
  'sv-terastal-charizard-ex-battle-master-deck-pokemon-japan': 'SV: テラスタルリザードンex バトルマスターデッキ',
  'sv-venusaur-charizard-blastoise-special-deck-set-pokemon-japan': 'SV: フシギバナ・リザードン・カメックス スペシャルデッキセット',
  'sv-future-miraidon-ex-starter-deck-build-set-pokemon-japan': 'SV: 未来のミライドンex スターターデッキ&ビルドセット',
  'sv-ancient-koraidon-ex-starter-deck-build-set-pokemon-japan': 'SV: 古代のコライドンex スターターデッキ&ビルドセット',
  'pokemon-tcg-classic-venusaur-pokemon-japan': 'ポケモンTCGクラシック: フシギバナ',
  'pokemon-tcg-classic-charizard-pokemon-japan': 'ポケモンTCGクラシック: リザードン',
  'pokemon-tcg-classic-blastoise-pokemon-japan': 'ポケモンTCGクラシック: カメックス',
  'wcs23-2023-world-championships-yokohama-deck-pikachu-pokemon-japan': 'WCS23: 2023 ワールドチャンピオンシップス 横浜デッキ ピカチュウ',
  'special-box-collections-pokemon-japan': 'スペシャルBOXコレクション',
  'battle-academy-pokemon-japan': 'バトルアカデミー',

  // === S (Sword & Shield) 時代 ===
  's12a-vstar-universe-pokemon-japan': 'S12a: VSTARユニバース',
  's12-paradigm-trigger-pokemon-japan': 'S12: パラダイムトリガー',
  's11a-incandescent-arcana-pokemon-japan': 'S11a: 白熱のアルカナ',
  's11-lost-abyss-pokemon-japan': 'S11: ロストアビス',
  's10b-pokemon-go-pokemon-japan': 'S10b: ポケモンGO',
  's10a-dark-phantasma-pokemon-japan': 'S10a: ダークファンタズマ',
  's10p-space-juggler-pokemon-japan': 'S10P: スペースジャグラー',
  's10d-time-gazer-pokemon-japan': 'S10D: タイムゲイザー',
  's9a-battle-region-pokemon-japan': 'S9a: バトルリージョン',
  's9-star-birth-pokemon-japan': 'S9: スターバース',
  's8b-vmax-climax-pokemon-japan': 'S8b: VMAXクライマックス',
  's8a-25th-anniversary-collection-pokemon-japan': 'S8a: 25thアニバーサリーコレクション',
  's8a-g-25th-anniversary-golden-box-pokemon-japan': 's8a-G: 25thアニバーサリー ゴールデンBOX',
  's8-fusion-arts-pokemon-japan': 'S8: フュージョンアーツ',
  's7d-skyscraping-perfection-pokemon-japan': 'S7D: 摩天パーフェクト',
  's7r-blue-sky-stream-pokemon-japan': 'S7R: 蒼空ストリーム',
  's6a-eevee-heroes-pokemon-japan': 'S6a: イーブイヒーローズ',
  's6k-jet-black-spirit-pokemon-japan': 'S6K: 漆黒のガイスト',
  's6h-silver-lance-pokemon-japan': 'S6H: 白銀のランス',
  's5a-peerless-fighters-pokemon-japan': 'S5a: 双璧のファイター',
  's5r-rapid-strike-master-pokemon-japan': 'S5R: 連撃マスター',
  's5i-single-strike-master-pokemon-japan': 'S5I: 一撃マスター',
  's4a-shiny-star-v-pokemon-japan': 'S4a: シャイニースターV',
  's4-amazing-volt-tackle-pokemon-japan': 'S4: 仰天のボルテッカー',
  's3a-legendary-heartbeat-pokemon-japan': 'S3a: 伝説の鼓動',
  's3-infinity-zone-pokemon-japan': 'S3: ムゲンゾーン',
  's2a-explosive-walker-pokemon-japan': 'S2a: 爆炎ウォーカー',
  's2-rebellion-crash-pokemon-japan': 'S2: 反逆クラッシュ',
  's1a-vmax-rising-pokemon-japan': 'S1a: VMAXライジング',
  's1w-sword-pokemon-japan': 'S1W: ソード',
  's1h-shield-pokemon-japan': 'S1H: シールド',
  's-p-sword-shield-promos-pokemon-japan': 'S-P: ソード&シールド プロモ',
  'si-start-deck-100-pokemon-japan': 'SI: スタートデッキ100',
  'sp6-vstar-special-set-pokemon-japan': 'sp6: VSTARスペシャルセット',
  'sp5-v-union-special-card-sets-pokemon-japan': 'sp5: V-UNIONスペシャルカードセット',
  'sp4-eevee-heroes-vmax-special-set-pokemon-japan': 'sp4: イーブイヒーローズ VMAXスペシャルセット',
  'sp2-vmax-special-set-pokemon-japan': 'sp2: VMAXスペシャルセット',
  'sp1-zacian-zamazenta-box-pokemon-japan': 'sp1: ザシアン+ザマゼンタ BOX',
  'ss-gengar-vmax-high-class-deck-pokemon-japan': 'SS: ゲンガーVMAX ハイクラスデッキ',
  'ss-inteleon-vmax-high-class-deck-pokemon-japan': 'SS: インテレオンVMAX ハイクラスデッキ',
  'ss-silver-lance-jet-black-spirit-jumbo-pack-set-pokemon-japan': 'SS: 白銀のランス&漆黒のガイスト ジャンボパックセット',
  'sf-single-strike-rapid-strike-premium-trainer-boxes-pokemon-japan': 'sF: 一撃&連撃 プレミアムトレーナーBOX',
  'sd-v-starter-decks-pokemon-japan': 'sD: Vスタートデッキ',
  'sc-charizard-starter-set-vmax-pokemon-japan': 'sC: リザードン スターターセットVMAX',
  'sc-grimmsnarl-starter-set-vmax-pokemon-japan': 'sC: オーロンゲ スターターセットVMAX',
  'sc2-charizard-starter-set-vmax-2-pokemon-japan': 'sC2: リザードン スターターセットVMAX 2',
  'sb-sword-shield-premium-trainer-box-pokemon-japan': 'sB: ソード&シールド プレミアムトレーナーBOX',
  'sn-start-deck-100-corocoro-comic-version-pokemon-japan': 'sN: スタートデッキ100 コロコロコミックver.',
  'sld-darkrai-starter-set-vstar-pokemon-japan': 'sLD: ダークライ スターターセットVSTAR',
  'sll-lucario-starter-set-vstar-pokemon-japan': 'sLL: ルカリオ スターターセットVSTAR',
  'sk-vstar-premium-trainer-box-pokemon-japan': 'sK: VSTARプレミアムトレーナーBOX',
  'sj-zacian-zamazenta-vs-eternatus-special-deck-set-pokemon-japan': 'sJ: ザシアン&ザマゼンタ vs ムゲンダイナ スペシャルデッキセット',
  's8a-p-promo-card-pack-25th-anniversary-edition-pokemon-japan': 's8a-P: プロモカードパック 25thアニバーサリーedition',
  'sef-venusaur-starter-set-vmax-pokemon-japan': 'sEF: フシギバナ スターターセットVMAX',
  'sek-blastoise-starter-set-vmax-pokemon-japan': 'sEK: カメックス スターターセットVMAX',
  'sh-sword-shield-family-pokemon-card-game-pokemon-japan': 'sH: ソード&シールド ファミリーポケモンカードゲーム',
  's0-charizard-vstar-vs-rayquaza-vmax-special-deck-set-pokemon-japan': 's0: リザードンVSTAR vs レックウザVMAX スペシャルデッキセット',
  'spd-deoxys-vstar-vmax-high-class-deck-pokemon-japan': 'sPD: デオキシスVSTAR&VMAX ハイクラスデッキ',
  'spz-zeraora-vstar-vmax-high-class-deck-pokemon-japan': 'sPZ: ゼラオラVSTAR&VMAX ハイクラスデッキ',
  'sa-water-starter-set-v-pokemon-japan': 'sA: 水タイプ スターターセットV',
  'sa-fighting-starter-set-v-pokemon-japan': 'sA: 闘タイプ スターターセットV',
  'sa-lightning-starter-set-v-pokemon-japan': 'sA: 雷タイプ スターターセットV',
  'sa-fire-starter-set-v-pokemon-japan': 'sA: 炎タイプ スターターセットV',
  'sa-grass-starter-set-v-pokemon-japan': 'sA: 草タイプ スターターセットV',

  // === SM (Sun & Moon) 時代 ===
  'sm12a-tag-team-gx-tag-all-stars-pokemon-japan': 'SM12a: TAG TEAM GX タッグオールスターズ',
  'sm12-alter-genesis-pokemon-japan': 'SM12: オルタージェネシス',
  'sm11b-dream-league-pokemon-japan': 'SM11b: ドリームリーグ',
  'sm11a-remix-bout-pokemon-japan': 'SM11a: リミックスバウト',
  'sm11-miracle-twin-pokemon-japan': 'SM11: ミラクルツイン',
  'sm10b-sky-legend-pokemon-japan': 'SM10b: スカイレジェンド',
  'sm10a-gg-end-pokemon-japan': 'SM10a: GGエンド',
  'sm10-double-blaze-pokemon-japan': 'SM10: ダブルブレイズ',
  'sm9b-full-metal-wall-pokemon-japan': 'SM9b: フルメタルウォール',
  'sm9a-night-unison-pokemon-japan': 'SM9a: ナイトユニゾン',
  'sm9-tag-bolt-pokemon-japan': 'SM9: タッグボルト',
  'sm8b-gx-ultra-shiny-pokemon-japan': 'SM8b: GXウルトラシャイニー',
  'sm8a-dark-order-pokemon-japan': 'SM8a: ダークオーダー',
  'sm8-super-burst-impact-pokemon-japan': 'SM8: 超爆インパクト',
  'sm7b-fairy-rise-pokemon-japan': 'SM7b: フェアリーライズ',
  'sm7a-thunderclap-spark-pokemon-japan': 'SM7a: 迅雷スパーク',
  'sm7-sky-splitting-charisma-pokemon-japan': 'SM7: 裂空のカリスマ',
  'sm6b-champion-road-pokemon-japan': 'SM6b: チャンピオンロード',
  'sm6a-dragon-storm-pokemon-japan': 'SM6a: ドラゴンストーム',
  'sm6-forbidden-light-pokemon-japan': 'SM6: 禁断の光',
  'sm5-ultra-force-pokemon-japan': 'SM5+: ウルトラフォース',
  'sm5m-ultra-moon-pokemon-japan': 'SM5M: ウルトラムーン',
  'sm5s-ultra-sun-pokemon-japan': 'SM5S: ウルトラサン',
  'sm4-gx-battle-boost-pokemon-japan': 'SM4+: GXバトルブースト',
  'sm4a-ultradimensional-beasts-pokemon-japan': 'SM4A: ウルトラビースト',
  'sm4s-awakened-heroes-pokemon-japan': 'SM4S: 覚醒の勇者',
  'sm3-shining-legends-pokemon-japan': 'SM3+: ひかる伝説',
  'sm3h-to-have-seen-the-battle-rainbow-pokemon-japan': 'SM3H: 闘う虹を見たか',
  'sm3n-darkness-that-consumes-light-pokemon-japan': 'SM3N: 光を喰らう闇',
  'sm2-facing-a-new-trial-pokemon-japan': 'SM2+: 新たなる試練の向こう',
  'sm2k-islands-await-you-pokemon-japan': 'SM2K: キミを待つ島々',
  'sm2l-alolan-moonlight-pokemon-japan': 'SM2L: アローラの月光',
  'sm1-enhanced-expansion-pack-sun-moon-pokemon-japan': 'sm1+: 強化拡張パック サン&ムーン',
  'sm1s-collection-sun-pokemon-japan': 'SM1S: コレクション サン',
  'sm1m-collection-moon-pokemon-japan': 'SM1M: コレクション ムーン',
  'sm-the-best-of-xy-pokemon-japan': 'SM: THE BEST OF XY',
  'sm-p-sun-moon-promos-pokemon-japan': 'SM-P: サン&ムーン プロモ',
  'sm0-pikachu-s-new-friends-pokemon-japan': 'SM0: ピカチュウの新しい仲間',
  'smm-tag-team-gx-starter-sets-pokemon-japan': 'smM: TAG TEAM GX スターターセット',
  'smj-tag-team-gx-premium-trainer-box-pokemon-japan': 'smJ: TAG TEAM GX プレミアムトレーナーBOX',
  'smh-gx-starter-decks-pokemon-japan': 'smH: GXスタートデッキ',
  'smk-trainer-battle-decks-pokemon-japan': 'smK: トレーナーバトルデッキ',
  'sml-sun-moon-family-pokemon-card-game-pokemon-japan': 'smL: サン&ムーン ファミリーポケモンカードゲーム',
  'smp2-great-detective-pikachu-pokemon-japan': 'smP2: 名探偵ピカチュウ',
  'smp1-rockruff-full-power-deck-pokemon-japan': 'smP1: イワンコ フルパワーデッキ',
  'sma-sun-moon-starter-set-pokemon-japan': 'smA: サン&ムーン スターターセット',
  'smb-premium-trainer-box-pokemon-japan': 'smB: プレミアムトレーナーBOX',
  'smc-tapu-bulu-gx-enhanced-starter-set-pokemon-japan': 'smC: カプ・ブルルGX 強化スターターセット',
  'smd-ash-vs-team-rocket-deck-kit-pokemon-japan': 'smD: サトシ vs ロケット団 デッキキット',
  'sme-solgaleo-gx-lunala-gx-legendary-starter-set-pokemon-japan': 'smE: ソルガレオGX&ルナアーラGX レジェンダリースターターセット',
  'smf-ultra-sun-ultra-moon-premium-trainer-box-pokemon-japan': 'smF: ウルトラサン&ウルトラムーン プレミアムトレーナーBOX',
  'smi-flareon-gx-vaporeon-gx-jolteon-gx-starter-sets-pokemon-japan': 'smI: ブースターGX・シャワーズGX・サンダースGX スターターセット',

  // === XY 時代 ===
  'cp6-expansion-pack-20th-anniversary-pokemon-japan': 'CP6: 拡張パック 20thアニバーサリー',
  'cp5-mythical-legendary-dream-shine-collection-pokemon-japan': 'CP5: 幻・伝説ドリームキラコレクション',
  'cp4-premium-champion-pack-pokemon-japan': 'CP4: プレミアムチャンピオンパック',
  'cp3-pokekyun-collection-pokemon-japan': 'CP3: ポケキュンコレクション',
  'cp2-legendary-shine-collection-pokemon-japan': 'CP2: レジェンダリーシャインコレクション',
  'cp1-magma-gang-vs-aqua-gang-double-crisis-pokemon-japan': 'CP1: マグマ団 vs アクア団 ダブルクライシス',
  'xy11-br-cruel-traitor-pokemon-japan': 'XY11-Br: 冷酷の反逆者',
  'xy11-bb-fever-burst-fighter-pokemon-japan': 'XY11-Bb: 爆熱の闘士',
  'xy10-awakening-psychic-king-pokemon-japan': 'XY10: 覚醒の勇者',
  'xy9-rage-of-the-broken-heavens-pokemon-japan': 'XY9: 破天の怒り',
  'xy8-br-red-flash-pokemon-japan': 'XY8-Br: レッドフラッシュ',
  'xy8-bb-blue-shock-pokemon-japan': 'XY8-Bb: ブルーショック',
  'xy7-bandit-ring-pokemon-japan': 'XY7: バンデットリング',
  'xy6-emerald-break-pokemon-japan': 'XY6: エメラルドブレイク',
  'xy5-bt-tidal-storm-pokemon-japan': 'XY5-Bt: タイダルストーム',
  'xy5-bg-gaia-volcano-pokemon-japan': 'XY5-Bg: ガイアボルケーノ',
  'xy4-phantom-gate-pokemon-japan': 'XY4: ファントムゲート',
  'xy3-rising-fist-pokemon-japan': 'XY3: ライジングフィスト',
  'xy2-wild-blaze-pokemon-japan': 'XY2: ワイルドブレイズ',
  'xy-bx-collection-x-pokemon-japan': 'XY-Bx: コレクションX',
  'xy-by-collection-y-pokemon-japan': 'XY-By: コレクションY',
  'xy-p-xy-promos-pokemon-japan': 'XY-P: XYプロモ',
  'xy-beginning-set-pokemon-japan': 'XYはじめてセット',
  'break-starter-pack-pokemon-japan': 'BREAKスターターパック',

  // === 旧裏 / その他 ===
  'japanese-cd-promo-pokemon-japan': 'CDプロモ',
  'expansion-pack-pokemon-japan': '第1弾 拡張パック',
  'expansion-pack-no-rarity-pokemon-japan': '第1弾 拡張パック (レアリティなし)',
  'pokemon-jungle-pokemon-japan': 'ポケモンジャングル',
  'mystery-of-the-fossils-pokemon-japan': '化石の秘密',
  'rocket-gang-pokemon-japan': 'ロケット団',
  'gym-challenge-pokemon-japan': 'ジムチャレンジ',
  'challenge-from-the-darkness-pokemon-japan': '闇からの挑戦',
  'leaders-stadium-pokemon-japan': 'リーダーズスタジアム',
  'gold-silver-to-a-new-world-pokemon-japan': '金、銀、新世界へ…',
  'crossing-the-ruins-pokemon-japan': '遺跡をこえて…',
  'awakening-legends-pokemon-japan': '目覚める伝説',
  'darkness-and-to-light-pokemon-japan': '闇、そして光へ…',
  'pokemon-web-pokemon-japan': 'ポケモンWeb',
  'pokemon-vs-pokemon-japan': 'ポケモンVS',
  'southern-island-pokemon-japan': 'サザンアイランド',
  'corocoro-promotional-cards-pokemon-japan': 'コロコロプロモカード',
}

/**
 * セットIDから日本語名を取得（マッピングがなければ英語名を返す）
 */
export function getSetNameJa(id: string, fallbackName: string): string {
  return SET_NAME_JA[id] || fallbackName
}

/**
 * セットIDからset_code（例: "SV10", "M3", "SLD"）を抽出
 * "sv10-the-glory-of-team-rocket-pokemon-japan" → "SV10"
 * "m3-nihil-zero-pokemon-japan" → "M3"
 * "sld-darkrai-starter-set-vstar-pokemon-japan" → "SLD"
 * R12-22: 数字なしのコード（SLD, SK等）にも対応
 */
export function extractSetCode(setId: string): string | null {
  const match = setId.match(/^([a-z]{1,5}\d*[a-z]?)-/i)
  return match ? match[1].toUpperCase() : null
}

/**
 * release_dateから年を抽出
 * "2026-01-23" → 2026
 */
export function extractReleaseYear(releaseDate: string | null): number | null {
  if (!releaseDate) return null
  const year = parseInt(releaseDate.substring(0, 4))
  return isNaN(year) ? null : year
}
